#!/usr/bin/env bash
# Filter a list of changed files to exclude generated/noise files.
#
# Reads a list of file paths (one per line) from the file given as $1.
# Prints surviving paths (one per line) to stdout. Surviving means:
#   - path does NOT match the exclude-path glob list, AND
#   - file's first 5 lines do NOT contain a generated-marker (unless the
#     file is under a migration path, which is exempt).
#
# Usage: filter-diff.sh <changed-files-list>
#
# Specs: specs/2026-05-15-diff-filtering/requirements.md

set -euo pipefail

CHANGED_FILES="${1:?usage: filter-diff.sh <changed-files-list>}"

EXCLUDE_PATH_GLOBS=(
  '*/package-lock.json' 'package-lock.json'
  '*/yarn.lock' 'yarn.lock'
  '*/pnpm-lock.yaml' 'pnpm-lock.yaml'
  '*/bun.lock' 'bun.lock'
  '*/bun.lockb' 'bun.lockb'
  '*/poetry.lock' 'poetry.lock'
  '*/Pipfile.lock' 'Pipfile.lock'
  '*/uv.lock' 'uv.lock'
  '*/Cargo.lock' 'Cargo.lock'
  '*/go.sum' 'go.sum'
  '*/composer.lock' 'composer.lock'
  '*/Gemfile.lock' 'Gemfile.lock'
  '*.min.js' '*.min.css' '*.min.mjs'
  '*.bundle.js' '*.bundle.css'
  '*.map'
  'dist/*' '*/dist/*'
  'build/*' '*/build/*'
  '.next/*' '*/.next/*'
  'out/*' '*/out/*'
)

MIGRATION_GLOBS=(
  '*/migrations/*' 'migrations/*'
  '*/migrate/*' 'migrate/*'
  'db/migrate/*'
)

CONTENT_MARKERS=(
  '@generated'
  'Code generated by'
  'DO NOT EDIT'
  'auto-generated'
  'THIS FILE IS GENERATED'
)

matches_any_glob() {
  local path="$1"
  shift
  local pattern
  for pattern in "$@"; do
    # shellcheck disable=SC2053
    if [[ "$path" == $pattern ]]; then
      return 0
    fi
  done
  return 1
}

is_path_excluded() {
  matches_any_glob "$1" "${EXCLUDE_PATH_GLOBS[@]}"
}

is_migration_path() {
  matches_any_glob "$1" "${MIGRATION_GLOBS[@]}"
}

has_generated_marker() {
  local path="$1"
  local content=""
  if git cat-file -e "HEAD:$path" 2>/dev/null; then
    content=$(git show "HEAD:$path" 2>/dev/null | head -n 5 || true)
  elif [ -f "$path" ]; then
    content=$(head -n 5 "$path")
  fi
  [ -z "$content" ] && return 1
  local marker
  for marker in "${CONTENT_MARKERS[@]}"; do
    if printf '%s' "$content" | grep -qiF -- "$marker"; then
      return 0
    fi
  done
  return 1
}

while IFS= read -r file; do
  [ -z "$file" ] && continue
  if is_path_excluded "$file"; then
    continue
  fi
  if has_generated_marker "$file" && ! is_migration_path "$file"; then
    continue
  fi
  printf '%s\n' "$file"
done < "$CHANGED_FILES"
